spring:
  application:
    name: aeronex

  datasource:
    url: jdbc:postgresql://localhost:5432/aeronex
    username: aeronex
    password: aeronex
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8080
